### ISSUE TITLE
Odd URL behaviour with slashes

### ISSUE THREAD

**Issue by nandos** [tag1consulting/goose#337] opened 2021-07-26 12:11 UTC
I'm trying to make a request to one of our internal APIs, it lives on `api.preprod.nandos.services/orders`.

I'm running `cargo run -- --host https://api.preprod.nandos.services/orders`, and the load test it's pointed at `/query/:`
```let request = user.goose_post("/query").await?.header("AUTHORIZATION", cheeky).json(json);```

This results in a `404 Not Found`:

```Ok(Response { url: Url { scheme: "https", host: Some(Domain("api.preprod.nandos.services")), port: None, path: "/query", query: None, fragment: None }, status: 404, headers: {"date": "Mon, 26 Jul 2021 12:01:37 GMT", "server": "istio-envoy", "connection": "close", "content-length": "0"} })```

It's stripping the `/orders` bit, but I'm not sure if this is the correct behaviour? Obviously I can just do `/orders/query` in the path but it's not as nice because ideally we use these load tests on other services without having to recompile for specific APIs to change the URL.

**Comment by jeremyandrews** [comment] 2021-07-26 15:38
It looks like this is a bug in how Goose is building URLs. It seems to make a bad assumption that the `base_url` can't include a path. I don't have time to write a fix today, but will aim to get a fix out soon -- PRs are also welcome!

**Comment by jeremyandrews** [comment] 2021-07-27 07:05
See https://github.com/tag1consulting/goose/pull/338

The issue is that you need to use a "relative" path (one that doesn't start with a `/`), instead of an absolute path (one that does start with a `/`).

In your example above, specify your URL as `orders/` instead of as `/orders/` and it will work as you expect.

**Comment by jeremyandrews** [comment] 2021-08-19 05:35
A test was added to the code-base to ensure this works, closing.

**Closed by jeremyandrews** 2021-08-19 05:35 UTC
Labels: documentation
