### ISSUE TITLE
the trait `From<reqwest::error::Error>` is not implemented for `Box<TransactionError>`

### ISSUE THREAD

**Issue by huangjj27** [tag1consulting/goose#532] opened 2022-12-25 14:01 UTC
minimal repeatable code snippet:
```rust
async fn post_data(user: &mut GooseUser) -> TransactionResult {
    #[derive(Serialize)]
    #[serde(rename_all = "camelCase")]
    struct Json {
        data: Data,
    }

  let json = Json {
        data: Data {
           // omitted
        },
    };
    let mut goose = user
        .post_json("my/url", &json)
        .await?;
    let res = goose.response?;
}
```

then:
```cargo
> cargo +nightly check                                     
    Checking myapp v0.1.0 (/path/to/my/app)
error[E0277]: `?` couldn't convert the error to `Box<TransactionError>`
  --> /path/to/my/app/src/main.rs:42:42
   |
42 |     let res = goose.response?;
   |                             ^ the trait `From<reqwest::error::Error>` is not implemented for `Box<TransactionError>`
   |
   = note: the question mark operation (`?`) implicitly performs a conversion on the error value using the `From` trait
   = help: the following other types implement trait `From<T>`:
             <Box<(dyn StdError + 'a)> as From<E>>
             <Box<(dyn StdError + 'static)> as From<&str>>
             <Box<(dyn StdError + 'static)> as From<Cow<'a, str>>>
             <Box<(dyn StdError + 'static)> as From<std::string::String>>
             <Box<(dyn StdError + Send + Sync + 'a)> as From<&str>>
             <Box<(dyn StdError + Send + Sync + 'a)> as From<Cow<'b, str>>>
             <Box<(dyn StdError + Send + Sync + 'a)> as From<E>>
             <Box<(dyn StdError + Send + Sync + 'static)> as From<std::string::String>>
           and 18 others
   = note: required for `Result<(), Box<TransactionError>>` to implement `FromResidual<Result<Infallible, reqwest::error::Error>>`

For more information about this error, try `rustc --explain E0277`.
error: could not compile `myapp` due to previous error
```

a quick fix is to wrap the error into a `Box`:
```rust
   // line 42
    let res = goose.response
        .map_err(|e| Box::new(TransactionError::Reqwest(e)))?;
```

**Comment by jeremyandrews** [comment] 2022-12-26 07:32
Closing as duplicate of #531

**Closed by jeremyandrews** 2022-12-26 07:32 UTC

**Comment by huangjj27** [comment] 2022-12-26 11:42
oh，I must have reposted this incidently. sorry～

**Comment by jeremyandrews** [comment] 2022-12-26 11:47
Not a problem, thanks for the bug report!
